name: Example useage of the inputs context in a manually triggered workflow

on:
  workflow_dispatch:
    # inputs 定义一组输入参数，为触发 workflow 时提供参数
    # inputs 也可以从 jobs.job_id.with 传递给 可复用的 workflow
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean

jobs:
  deply:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Deploy build to target.
        run: deploy --build ${{ inputs.build_id }} --target ${{ inputs.deploy_target }}
