name: Secrets context example
on: [pull_request_target]

jobs:
  triage:
    runs-on: ubuntu-latest
    # 定义 名字为 triage 的 job 需要的权限级别
    permissions:
      # 指定 job 需要对仓库内容具有读取的权限
      contents: read
      # 指定 jb 需要对拉去请求具有写入权限。
      pull-requests: write
    steps:
      # actions/labler@v4 action 用来标记 github 仓库中的问题和拉去请求的 操作.
      - uses: actions/labeler@v4
        # with 指定 action 的参数
        with:
          # 指定 action 需要的仓库 访问 token，GITHUB_TOKEN 是一个 github 自动创建的仓库密钥，用于授权 Actions 访问仓库和 执行相关操作
          repo-token: ${{ secrets.GITHUB_TOKEN }}
