name: Using inputs and secrets in a reusable workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      envInput:
        type: string
        default: "production"
    secrets:
      envPAT:
        required: true

jobs:
  reuseable_workflow_job:
    runs-on: ubuntu-latest
    environment: ${{inputs.envInput}}
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{secrets.envPAT}}
          configuration-path: ${{inputs.config-path}}
